fos_rest:
  param_fetcher_listener: true
  allowed_methods_listener: true
  view:
    serialize_null: true
    view_response_listener: true
  serializer:
    serialize_null: true
  format_listener:
    rules:
      fallback_format: json
  body_listener: true
  zone:
    - { path: ^/api/* }
