version: '3.7'

services:
    db:
        image: mariadb:lts
        volumes:
            - db_app:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 9906:3306
        networks:
            - booking
    php:
        build:
            context: .docker/php
            args:
                TIMEZONE: ${TIMEZONE}
        depends_on:
            - db
        volumes:
            - ./:/var/www/symfony/
            - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini:rw
        networks:
            - booking
    nginx:
        build:
            context: .docker/nginx
        volumes:
            - ./:/var/www/symfony/
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:rw
        ports:
            - 90:80
        networks:
            - booking
        env_file:
            - ./.docker/.env.nginx

volumes:
    db_app:
        driver: local

networks:
    booking:
        external: true
